### ISSUE TITLE
json[] in transformers result in codegen errors

### ISSUE THREAD

**Issue by afkham** [ballerina-lang/ballerina#5002]
**Description:**
```ballerina
transformer <RegistrationRequest req, json j> regReqToJson() {
    j.transactionId = req.transactionId;
    j.participantId = req.participantId;
    json[] protocols = req.participantProtocols.map(
                                               function (Protocol proto) returns (json) {
                                                   json j2 = {name:proto.name, url:proto.url};
                                                   return j2;
                                               });
    j.participantProtocols = protocols;
}
```
Adding the above code segment to your Ballerina program will result in the following error (in the bre.log)

[2018-03-05 18:22:24,744] ERROR {org.ballerinalang.launcher.Main} - ballerina: internal error occurred 
java.lang.AssertionError
        at org.wso2.ballerinalang.compiler.tree.BLangNodeVisitor.visit(BLangNodeVisitor.java:288)
        at org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef.accept(BLangSimpleVarRef.java:59)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1202)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:2479)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangAssignment.accept(BLangAssignment.java:84)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1202)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:474)
        at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:53)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1202)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.processWorker(CodeGenerator.java:1502)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visitInvokableNode(CodeGenerator.java:1480)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:462)
        at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:41)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1202)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.visit(CodeGenerator.java:410)
        at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:145)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genNode(CodeGenerator.java:1202)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.genPackage(CodeGenerator.java:1210)
        at org.wso2.ballerinalang.compiler.codegen.CodeGenerator.generate(CodeGenerator.java:310)
        at org.wso2.ballerinalang.compiler.Compiler.gen(Compiler.java:167)
        at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:113)
        at org.ballerinalang.launcher.LauncherUtils.compile(LauncherUtils.java:230)
        at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:72)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:259)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:63)

The same code in a function works, so this is a transformer specific issue. The following function works:

```ballerina
function regReqToJson (RegistrationRequest req) returns (json) {
    json j = {};
    j.transactionId = req.transactionId;
    j.participantId = req.participantId;
    json[] protocols = req.participantProtocols.map(
                                               function (Protocol proto) returns (json) {
                                                   json j2 = {name:proto.name, url:proto.url};
                                                   return j2;
                                               });
    j.participantProtocols = protocols;
    return j;
}
```

**Comment by keizer619** [comment]
This run time issue happens for Structs and for iterable operations without lambda too. Even without invoking the transformer

``` ballerina
struct Person {
    Vehicle [] vehicles;
}

struct Vehicle {
   string vid; string vehicleType; float cylinderCapacity;
}

struct Employee {
   int numberOfVehicles;
}

transformer<Person source,Employee target> {
   target.numberOfVehicles = source.vehicles.count();
}
```

**Comment by keizer619** [comment]
Fixed in following PR
https://github.com/ballerina-lang/ballerina/pull/5021

**Comment by djkevincr** [comment]
PR https://github.com/ballerina-lang/ballerina/pull/5021 addresses the issue . Hence closing the issue.
